version: "3.3"
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  webapp:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: social-lifestyle-webapp
    depends_on:
      - backend
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: on-failure
    container_name: backend
    # volumes:
    #   - /app/node_modules
    #   - ./backend:/app
    depends_on:
      - mongo
  mongo:
    container_name: social-lifestyle-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=sociallifestyle
    volumes:
      # - ./data/:/data/db/ // check problems with volume
      - ./initialConfig/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
